apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment  
  namespace: raju  
  labels:
    app: new-app  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-app  
  template:
    metadata:
      labels:
        app: new-app  
    spec:
      containers:
        - name: new-app  
          image: 2024dock/raju-app:1.3  
          ports:
            - containerPort: 3000  
