apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raju-app
  namespace: flux-system
spec:
  releaseName: raju-app
  interval: 1m
  chart:
    spec:
      chart: ./raju-app-chart  # This path must exist in your repo!
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: "0.1.0"
  values:
    image:
      repository: 2024dock/raju-app
      tag: "25.3.1"
