apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raju-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: raju-app-chart  # Ensure this exists!
      sourceRef:
        kind: GitRepository
        name: flux-system  # Ensure this matches your source
        namespace: flux-system
      version: "0.1.0"
  values:
    image:
      repository: 2024dock/raju-app
      tag: "25.3.1"
    replicaCount: 2
