apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: raju-app
spec:
  resources:
    - deployment.yaml
    - service.yaml
  commonLabels:
    app: raju-app
  namespace: default  # Specify the namespace here as well
