apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - helmrelease.yaml

images:
  - name: 2024dock/raju-app
    newTag: "25.3.1"  # Updated to latest tag
