apiVersion: v1
kind: Service
metadata:
  name: raju-app-service
spec:
  selector:
    app: raju-app
  ports:
    - protocol: TCP
      port: 80  # External port to expose the service on
      targetPort: 3000  # Port inside the container
  type: LoadBalancer  # Exposes the service externally if using a cloud provider (use 'ClusterIP' for internal access only)
