apiVersion: v1
kind: Service
metadata:
  name: raju-app-service
  namespace: flux-system
  labels:
    app: raju-app
spec:
  selector:
    app: raju-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
