apiVersion: apps/v1
kind: Deployment
metadata:
  name: raju-app
  labels:
    app: raju-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: raju-app
  template:
    metadata:
      labels:
        app: raju-app
    spec:
      containers:
        - name: raju-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
