apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raju-app
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: raju-app-chart  # Name of the Helm chart in the repo
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: "0.1.0"
  values:
    image:
      repository: 2024dock/raju-app
      tag: "25.3.1"  # Change for new releases
    replicaCount: 2
    service:
      type: ClusterIP
      port: 80
