apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - helmrelease.yaml

images:
  - name: 2024dock/raju-app
    newTag: "1.4"  # Change this for new releases
