apiVersion: v1
kind: Service
metadata:
  name: raju-app
spec:
  selector:
    app: raju-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
