name: Tag and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and Push Git Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Update Kubernetes manifests with new tag
        run: sed -i "s|newTag: .*|newTag: ${{ github.event.inputs.version }}|" raju-app-chart/templates/kustomization.yaml

      - name: Commit and push changes
        run: |
          git add raju-app-chart/templates/kustomization.yaml
          git commit -m "Updated kustomization.yaml with new tag ${{ github.event.inputs.version }}"
          git push origin main

      - name: Flux Reconcile
        run: flux reconcile ks -n flux-system
